version: '3.8'

services:
  p2p-nft-widget:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_SYNAPSE_ACCESS_TOKEN=syt_YW1hbg_WuJBEoeZgOkIBgGCEVIC_3iJCEb
      - REACT_APP_SYNAPSE_URL=https://synapse.textrp.io
      - REACT_APP_MARKETPLACE_URL=https://bithomp.com
      - REACT_APP_ELEMENTS_URL=http://d-test-lilac.vercel.app
      - REACT_APP_BACKEND_URL=https://backend-dev.textrp.io
      - REACT_APP_XRPL_MAIN_NET_URL=wss://xrplcluster.com
      - REACT_APP_XRPL_TEST_NET_URL=wss://s.altnet.rippletest.net:51233
      - REACT_APP_BROKER_WALLET_ADDRESS = r9syfthWEycVKuy9bz2awsxrTNK3NBBT6h
      - REACT_APP_SYSTEM_WALLET_ADDRESS = rJGU5UbC4nBSAjLW9URHDbm4uuAEsfacVD
      - REACT_APP_BITHOMP_TOKEN = 0b833219-c387-4b3f-9606-0e4bd82e5862
    restart: unless-stopped
